### ISSUE TITLE
ng-dropdown-multiselect inside a ng-repeat not working

### ISSUE THREAD

**Issue by alenb** [dotansimha/angularjs-dropdown-multiselect#185]
**Plunker:**
http://plnkr.co/edit/3KN7ElsJ7XBcmTyQ7v3Q

**JS:**

```
$scope.autoRule = {
    data: [
        {
            id: 1,
            label: 'Option1'
        },
        {
            id: 2,
            label: 'Option2'
        },
        {
            id: 3,
            label: 'Option3'
        }
    ],
    settings: {
        enableSearch: true,
        scrollable: true,
        selectionLimit: 1
    },
    translation: {
        buttonDefaultText: 'Rule'
    }
};

$scope.invoicesTable = {
    invoice: {
        autoRules: []
    }
};
```

**HTML:**

```
<div ng-repeat="autoRule in autoRule.data track by $index">
    <div class="rule-auto" ng-dropdown-multiselect="" options="autoRule.data" selected-model="invoicesTable.invoice.autoRules[ $index ]" extra-settings="autoRule.settings" translation-texts="autoRule.translation"></div>
    <!-- <select ng-model="invoicesTable.invoice.autoRules[ $index ]" ng-options="autoRule as autoRule.label for autoRule in autoRule.data track by autoRule.id"></select> -->
</div>

{{ invoicesTable.invoice.autoRules | json }}
```

**Errors:**

```
TypeError: Cannot read property 'length' of undefined
    at n.$scope.getButtonText (https://rawgit.com/dotansimha/angularjs-dropdown-multiselect/master/dist/angularjs-dropdown-multiselect.min.js:1:5572)
    at fn (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:212:83), <anonymous>:4:230)
    at Object.get (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:116:1)
    at n.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:132:124)
    at n.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:135:269)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:19:437
    at Object.e [as invoke] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:39:156)
    at Ac.d (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:19:358)
    at Ac (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:20:151)
    at Zd (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:18:464)
```

```
TypeError: Cannot read property 'id' of undefined
    at n.$scope.isChecked (https://rawgit.com/dotansimha/angularjs-dropdown-multiselect/master/dist/angularjs-dropdown-multiselect.min.js:1:8186)
    at fn0 (eval at <anonymous> (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:212:83), <anonymous>:4:1338)
    at Object.get (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:116:1)
    at n.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:132:124)
    at n.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:135:269)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:19:437
    at Object.e [as invoke] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:39:156)
    at Ac.d (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:19:358)
    at Ac (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:20:151)
    at Zd (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.min.js:18:464)
```

**Comment by markgargan** [comment]
Hi there Alenb, 

              If you use the unminified file you can debug with a break point on the exact line and step through your problem. 
I think the length issue is because of this line 
if ($scope.settings.dynamicTitle && ($scope.selectedModel.length > 0 || (angular.isObject($scope.selectedModel) && _.keys($scope.selectedModel).length > 0))) {
          
on line 180.
It appears to be trying to set the button text before it creates the $scope.selectedModel. 

I had a similar problem; had the following directive located within an ng-repeat

<div ng-repeat="(key, value) in relations">
      <relation-directive></relation-directive>
</div>

I needed the relation-directive to create a multiselector setting the selected-model dynamically. I broke my heart trying to put the html that generates the multiselector into a template. However ultimately I could only solve it by generating a string representation of the html file on the fly in the relationDirective's link method and calling the compile function. 

var html = '';

    html += '<div class="form-group">';
    html += '   <label class="control-label col-xs-2 col-xs-offset-3" for="' + scope.relationName + '">' + scope.relationName + '</label>';
    html += '    <div class="col-xs-4" ng-dropdown-multiselect="" ';
    html += '            options="potentialRelatedData" autocomplete="off" ';
    html += '            selected-model="newEntity.' + scope.relationName + '"';
    html += '            extra-settings="extraSettings"';
    html += '            translation-texts="multiSelectText">';
    html += '    </div>';
    html += '</div>';
    elem.replaceWith($compile(html)(scope));

This is the only way that the select-model could be configured dynamically. I've seen the same thing with ng-model. 

Hope this helps. 
Mark.

**Comment by mcolegro** [comment]
I'm trying to do the same thing and I have been racking my brain trying to get the selected-model to be dynamic.

I saw this thread but don't completely understand your solution. Did you create your own directive (above) that writes out the syntax for the dropdown-multiselect directive?

**Comment by pkempenaers** [comment]
In v2 selected-model is always an array, beta.1 is now also available

**Comment by mittu123** [comment]
Thanks Markgargan, 
your solution worked for me, Cheers :) :)

**Comment by v29neil** [comment]
hey,  what about events?

```
<div 
class="rule-auto" 
ng-dropdown-multiselect="" 
options="autoRule.data" 
selected-model="invoicesTable.invoice.autoRules[ $index ]" 
extra-settings="autoRule.settings" 
translation-texts="autoRule.translation"
events="onSelect($index)"></div>
```

In documentation , events attribute should expect object.
Can i pass onSelect as function like this : 
```
              $scope.onSelect = function (index) {
                return {
                  onItemSelect: function (item) {
                    console.log('onItemSelect')
                    console.log(item)
                    console.log(index)

                  },
                  onItemDeselect: function (item) {
                    console.log('onItemDeselect')
                    console.log(item)
                    console.log(index)
                  },
                  onInitDone: function () {
                  }
                }
              };
```
It is giving this error -
```

angular.js:14800 Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: [[{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":{}},{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":{}}],[{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."},{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."}],[{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."},{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."}],[{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."},{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."}],[{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."},{"msg":"fn: regularInterceptedExpression","newVal":{},"oldVal":"..."}]]
http://errors.angularjs.org/1.6.9/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%7B%7D%7D%2C%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%7B%7D%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%2C%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%2C%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%2C%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%5D%2C%5B%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%2C%7B%22msg%22%3A%22fn%3A%20regularInterceptedExpression%22%2C%22newVal%22%3A%7B%7D%2C%22oldVal%22%3A%22...%22%7D%5D%5D
    at angular.js:116
    at Scope.$digest (angular.js:18418)
    at Scope.$apply (angular.js:18649)
    at done (angular.js:12627)
    at completeRequest (angular.js:12871)
    at XMLHttpRequest.requestLoaded (angular.js:12788)


```

any  help in using events will appreciated.
