### ISSUE TITLE
Problems after fresh install seem to be related to missing Lodash.

### ISSUE THREAD

**Issue by adambarthelson** [dotansimha/angularjs-dropdown-multiselect#8]
```
TypeError: undefined is not a function
    at Scope.$scope.isChecked (http://0.0.0.0:9000/bower_components/angularjs-dropdown-multiselect/src/angularjs-dropdown-multiselect.js:289:14)
    ...

TypeError: undefined is not a function
    at Scope.$scope.setSelectedItem (http://0.0.0.0:9000/bower_components/angularjs-dropdown-multiselect/src/angularjs-dropdown-multiselect.js:272:20)
    ...
```

I was able to fix the problem after including Lodash in my index.html, but you may want to mention in the guide to import Lodash along with angularjs-dropdown-multiselect in the future.

**Comment by adambarthelson** [comment]
![](http://i.imgur.com/6GipAQQ.gif)

**Comment by jsandeepm** [comment]
Hi,

I am running with below mentioned issue. Can you help?

TypeError: undefined is not a function
    at Scope.$scope.isChecked (http://localhost:8088/testing-decisions/js/local/lib/angular-dropdown/1.0/angularjs-dropdown-multiselect.js:286:30)

Line 286 : return _.findIndex($scope.selectedModel, getFindObj(id)) !== -1;


I have loaded 
angular.js(1.2.18)
lodash.js(latest version 3.0.0 ) 
/angularjs-dropdown-multiselect.js(latest version)

**Comment by adambarthelson** [comment]
Looks like either your underscore isn't installed correctly, or you're in a block where $scope isn't present.
console.log both before that line, what do you get sir?

**Comment by arvind-das** [comment]
Adding ngLodash to module and its js did not work for me . Still getting
 ReferenceError: _ is not defined
    at Scope.link.$scope.getButtonText (angularjs-dropdown-multiselect.js?compile=false:180)
Any ideas ?

**Comment by adambarthelson** [comment]
I assume the script for lodash isn't included in your index.html.

**Comment by arvind-das** [comment]
I added the script. Without that ngLodash module will not get loaded!
